name: peaman_ui_components
description: A prebuilt and highly customizable social media UI components package to be used on top of peaman package.
version: 0.0.3
homepage: https://peaman.web.app
repository: https://github.com/shrijanRegmi/peaman_ui_components
issue_tracker: https://github.com/shrijanRegmi/peaman_ui_components/issues

environment:
  sdk: ">=2.18.5 <3.0.0"
  flutter: ">=1.17.0"

publish_to: none

dependencies:
  cached_network_image: ^3.2.3
  flutter:
    sdk: flutter
  peaman:
    git:
      url: https://github.com/shrijanRegmi/peaman.git
      ref: new_version
  flutter_svg: ^1.1.6
  linkfy_text: ^1.1.5
  url_launcher: ^6.1.7
  google_fonts: ^4.0.3
  fluttertoast: ^8.1.2
  another_flushbar: ^1.12.29
  lottie: ^2.1.0
  image_picker: ^0.8.6
  timeago: ^3.3.0
  country_picker: ^2.0.19
  photo_view: ^0.14.0
  # image_downloader: ^0.31.0
  hooks_riverpod: ^2.3.2
  flutter_hooks: ^0.18.6
  flutter_screenutil: ^5.7.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  flutter_slidable: ^2.0.0
  flutter_keyboard_visibility: ^5.4.0
  metadata_fetch: ^0.4.1
  scroll_to_index: ^3.0.1
  video_thumbnail: ^0.5.3
  flutter_local_notifications: ^13.0.0
  cached_video_player: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/svgs/
    - assets/images/
    - assets/lotties/
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
